name: Java CI

# By default, this will run on Ubuntu Linux (ubuntu-latest)
# To change to (e.g.) MacOS:
# runs-on: macos-latest

on:
  push:
    branches:
    - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: cd S22; mvn test
