name: JavaCI

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'
          cache: maven
      - name: Build and test the selenium_demo with Maven
        run: cd F22/selenium_demo; mvn test
